// <auto-generated />
using System;
using FSI.SupportPointSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FSI.SupportPointSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FSI.SupportPointSystem.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("Cnpj");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("FSI.SupportPointSystem.Domain.Entities.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Sellers", (string)null);
                });

            modelBuilder.Entity("FSI.SupportPointSystem.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("Cpf");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("FSI.SupportPointSystem.Domain.Entities.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("CheckinDistanceMeters")
                        .HasColumnType("double");

                    b.Property<DateTime>("CheckinTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("CheckoutDistanceMeters")
                        .HasColumnType("double");

                    b.Property<string>("CheckoutSummary")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("CheckoutTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SellerId", "CheckoutTimestamp")
                        .HasDatabaseName("IX_Visits_Seller_ActiveOnly")
                        .HasFilter("`CheckoutTimestamp` IS NULL");

                    b.ToTable("Checkins", (string)null);
                });

            modelBuilder.Entity("FSI.SupportPointSystem.Domain.Entities.Customer", b =>
                {
                    b.OwnsOne("FSI.SupportPointSystem.Domain.ValueObjects.Coordinates", "LocationTarget", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Latitude")
                                .HasPrecision(12, 9)
                                .HasColumnType("decimal(12,9)")
                                .HasColumnName("LatitudeTarget");

                            b1.Property<decimal>("Longitude")
                                .HasPrecision(12, 9)
                                .HasColumnType("decimal(12,9)")
                                .HasColumnName("LongitudeTarget");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("LocationTarget")
                        .IsRequired();
                });

            modelBuilder.Entity("FSI.SupportPointSystem.Domain.Entities.Seller", b =>
                {
                    b.HasOne("FSI.SupportPointSystem.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("FSI.SupportPointSystem.Domain.Entities.Seller", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FSI.SupportPointSystem.Domain.Entities.Visit", b =>
                {
                    b.HasOne("FSI.SupportPointSystem.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FSI.SupportPointSystem.Domain.Entities.Seller", null)
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("FSI.SupportPointSystem.Domain.ValueObjects.Coordinates", "CheckinLocation", b1 =>
                        {
                            b1.Property<Guid>("VisitId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Latitude")
                                .HasPrecision(12, 9)
                                .HasColumnType("decimal(12,9)")
                                .HasColumnName("CheckinLatitude");

                            b1.Property<decimal>("Longitude")
                                .HasPrecision(12, 9)
                                .HasColumnType("decimal(12,9)")
                                .HasColumnName("CheckinLongitude");

                            b1.HasKey("VisitId");

                            b1.ToTable("Checkins");

                            b1.WithOwner()
                                .HasForeignKey("VisitId");
                        });

                    b.OwnsOne("FSI.SupportPointSystem.Domain.ValueObjects.Coordinates", "CheckoutLocation", b1 =>
                        {
                            b1.Property<Guid>("VisitId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Latitude")
                                .HasPrecision(12, 9)
                                .HasColumnType("decimal(12,9)")
                                .HasColumnName("CheckoutLatitude");

                            b1.Property<decimal>("Longitude")
                                .HasPrecision(12, 9)
                                .HasColumnType("decimal(12,9)")
                                .HasColumnName("CheckoutLongitude");

                            b1.HasKey("VisitId");

                            b1.ToTable("Checkins");

                            b1.WithOwner()
                                .HasForeignKey("VisitId");
                        });

                    b.Navigation("CheckinLocation")
                        .IsRequired();

                    b.Navigation("CheckoutLocation");
                });
#pragma warning restore 612, 618
        }
    }
}
